(defun format-simple(formatStr)
  "format the list"
  (interactive "splease input")
  (let ((all-str (buffer-substring-no-properties (point-min) (point-max))))
    (let ((lines (split-string all-str "\n")))
      (goto-char (point-min))
      (set-mark (point-max))
      (kill-region (region-beginning) (region-end))
      (goto-char (point-min))
     (while (> (length lines) 0)
       (setq line (car lines))
       (goto-char (point-max))
       (insert (concat (format formatStr line) "\n"))
       (Setq lines (cdr lines))))))
      
(provide 'format-simple)
